---
- name: Tasks Patch CentOS-7 RHEL-7
  hosts: os_yum
  become: true
  
  tasks:

    - name: Sleep for 30 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 30
      delegate_to: localhost
    
    - name: Install updates on CentOS-7 RHEL-7
      ansible.builtin.yum:
        name: '*'
        update_cache: true
        state: latest
      tags:
        - update-rhel7
...