---
# tasks file for patching RHEL-8 and CentOS-8
########################################################################################
#                                                                                      #
# --                                                                                   #
# Author: Joey Allen                                                                   #
#                                                                                      #
########################################################################################
#  Purpose: Playbook to perform 'dnf update' on selected hosts.                        #
#           ALL the packages with updates on the enabled repositories will be updated. #
#                                                                                      #
########################################################################################
### Supported OS: RHEL and CentOS                                                      #
########################################################################################

- name: Tasks Patch CentOS-8-9 RHEL-8-9
  hosts: os_dnf
  become: true

  tasks:
    - name: Install updates on CentOS-8-9 RHEL-8-9
      ansible.builtin.dnf:
        name: '*'
        update_cache: true
        state: latest
      tags:
        - update-rhel8-9
...